version: '3.3'

services:
    redis:
        image: redis:7.2-alpine
        ports:
            - '6379:6379'
        networks:
            - internal-net

networks:
    internal-net:
        name: internal-net
        external: true
